## Environment variables

# Development Database Parameters
DATABASE_USER_DEV: dev_ds_user
DATABASE_PASSWORD_DEV: DS0m1!pI!$0Y&%O4J#D3vDSm022
DATABASE_ACCOUNT_DEV: oma07528
DATABASE_NAME_DEV: DEV_GLOBAL_PARTNER
DATABASE_SCHEMA_DEV: ML

# Production Database Parameters
DATABASE_USER_PROD: prod_ecom_user
DATABASE_PASSWORD_PROD: Ia^z@Ws7MSTDzvnY*Et$t6mPx
DATABASE_ACCOUNT_PROD: oma07528
DATABASE_NAME_PROD: PROD_ECOM
DATABASE_SCHEMA_PROD: ML
